### ISSUE TITLE
Messaging inconsistency around email address when signing up

### ISSUE THREAD

**Issue by stkent** [DittoToday/BugTracker#9]
I tried to submit my information without an email address, as this was marked optional. However, the submission failed, indicating that an email address was required after all:

<img width="593" alt="screen shot 2015-11-03 at 10 13 12 pm" src="https://cloud.githubusercontent.com/assets/6463980/10928617/39fb8b26-8278-11e5-93d0-bd787ac3ea8a.png">

**Comment by michaelfdeberry** [comment]
Thanks for pointing this out. Seems to be a validation issue if you enter a space in the email field. I will get that worked out
